name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "发布版本号"
        required: true
        type: string

jobs:
  build_and_release:
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      PYTHONIOENCODING: utf-8
      PYTHONUTF8: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update resources
        run: python src/project.py update

      - name: Build all executables
        run: python src/project.py build --all

      - name: Generate Release Files
        run: python src/project.py release

      - name: Get Previous Tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: v1.0.0

      - name: Generate Changelog
        id: changelog
        run: |
          $previousTag = "${{ steps.previoustag.outputs.tag }}"
          $rawLog = git log "$previousTag..HEAD" --pretty=format:"- %s" | Out-String
          $changelog = $rawLog.Trim() -replace "`r`n", "`n" -replace "`n", "%0A"
          if ($changelog -notmatch '%0A$') {
            $changelog = "$changelog%0A"
          }

          @"
          CHANGELOG=$changelog
          "@ | Out-File -Append -Encoding utf8 $env:GITHUB_OUTPUT

        shell: pwsh

      - name: Set time
        run: |
          $time = [System.TimeZoneInfo]::ConvertTimeBySystemTimeZoneId((Get-Date), 'China Standard Time').ToString('yyyy-MM-dd HH:mm:ss')
          echo "TIME=$time" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: "release/*.zip"
          name: Release v${{ github.event.inputs.version }}
          tag_name: v${{ github.event.inputs.version }}
          body: |
            自动构建发布版本 v${{ github.event.inputs.version }}

            ## 更新日志
            ${{ steps.changelog.outputs.CHANGELOG }}

            详情可见[CHANGELOG](./CHANGELOG.md)。

            ## 发布信息
            发布时间：${{ env.TIME }} (GMT+8)
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: Asia/Shanghai
